import { loadSettings } from './config/settings';
import {
  loadClient, loadExtraClients, loadLocalProducts,
  loadOrderMeta, loadOrderApp, loadOrders, loadActiveStoreId, loadOrderMode,
  loadAllStoresCache, loadProductsCache,
} from './storage';
import { todayGMT3 } from './utils';
import type {
  AnalyticsPeriod, AnalyticsTab, AppPage, CartItem, CartTab, CategoryNode, CountryEntry,
  OrderApp, OrderMode, Product, SavedOrder, Shop,
} from './types';
import type { AppOrder, AppOrderPeriod, ModeratedProduct } from './api/types';

const _settings = loadSettings();
const _orders = loadOrders();
const _activeStoreId = loadActiveStoreId() || _orders[0]?.storeId || _settings.storeId;

export const state = {
  settings: _settings,
  categories: [] as CategoryNode[],
  selectedSubcategoryId: null as number | null,
  products: [] as Product[],
  productsLoading: false,
  productsError: '',
  categoriesLoading: false,
  categoriesError: '',
  activeStoreId: _activeStoreId,
  storesList: [] as Shop[],
  storesLoading: false,
  storesExpanded: false,
  cart: [] as CartItem[],
  productsCache: loadProductsCache(_activeStoreId),
  searchQuery: '',
  filterImport: false,
  countries: [] as CountryEntry[],
  countriesExpanded: false,
  cartTab: 'cart' as CartTab,
  client: loadClient(),
  clientSuggestHidden: false,
  extraClients: loadExtraClients(),
  orderMeta: loadOrderMeta(),
  currentPage: 'products' as AppPage,
  orders: _orders,
  expandedOrderId: null as string | null,
  ordersFilterFrom: todayGMT3(),
  ordersFilterTo: todayGMT3(),
  ordersFilterStore: '',
  ordersFilterStatus: '' as SavedOrder['status'] | '',
  ordersFilterAttention: false,
  ordersShowTrash: false,
  editingOrderId: null as string | null,
  vendorProducts: [] as Product[],
  vendorProductsLoading: false,
  pendingProducts: [] as ModeratedProduct[],
  pendingProductsLoading: false,
  pendingPage: 0,
  localProducts: loadLocalProducts(),
  showLocalProductForm: false,
  localProductForm: { name: '', price: '', productType: 'PIECE' },
  editingLocalProductId: null as string | null,
  localEditPrice: '',
  refsClientSearch: '',
  refsPage: 0,
  orderApp: loadOrderApp() as OrderApp,
  orderMode: loadOrderMode() as OrderMode,
  appClientExpanded: false,
  clientInfoPanel: null as null | 'menu' | 'phones' | 'addresses',
  detectedZone: '' as string,
  detectedZoneKm: null as number | null,
  detectedZoneLoading: false,
  prefetchTotal: 0,
  prefetchDone: 0,
  searchAllQuery: '',
  allStoresProducts: loadAllStoresCache(),
  allStoresLoading: false,
  mobilePanel: 'products' as 'products' | 'cart' | 'cats',
  analyticsTab: 'overview' as AnalyticsTab,
  analyticsPeriod: 'day' as AnalyticsPeriod,
  zoneGeoKey: '',
  mangoAccounts: [] as Array<{ operatorPhone: string }>,
  mangoMyPhone: '',
  appOrders: [] as AppOrder[],
  appOrdersLoading: false,
  appOrdersError: '',
  appOrdersPeriod: 'today' as AppOrderPeriod,
  appOrdersTotalCount: 0,
  appOrderLinked: null as string | null,
};
